# Generated by Django 4.2.3 on 2023-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_director_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(default='top_player@top.gun', max_length=254),
        ),
    ]
