# Generated by Django 4.2.3 on 2023-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_dressingroom_actor_dreesing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
